import {NextResponse} from "next/server";
const VERSION="LIDL-SEARCH-v21-20261001";
export async function GET(){
const r=await fetch("https://www.lidl.fi/h/kuivatuotteet/h10096095",{cache:"no-store",signal:AbortSignal.timeout(10000)});const html=await r.text();const m=html.match(/<script[^>]*id=["']__NUXT_DATA__["'][^>]*>([\s\S]*?)<\/script>/i);let store:unknown=null;
if(m){const a:unknown[]=JSON.parse(m[1]);const d=(v:unknown,depth=0):unknown=>{if(depth>6)return v;const x=typeof v==="number"&&Number.isInteger(v)&&v>=0&&v<a.length?a[v]:v;if(Array.isArray(x)&&["Ref","Reactive","EmptyRef"].includes(String(x[0])))return d(x[1],depth+1);return x};const root=a[92] as Record<string,unknown>;const p=d(root.useProductStore) as Record<string,unknown>;const g=d(root.useGlobalStore) as Record<string,unknown>;store={numFound:d(p.numFound),productsType:Array.isArray(d(p.products))?"array":typeof d(p.products),productsCount:Array.isArray(d(p.products))?(d(p.products) as unknown[]).length:null,categoryId:d(g.categoryId),pageId:d(g.pageId),masterQuery:d(g.masterQuery)}}
const tests=[["known-v2","?assortment=FI&locale=fi_FI&version=v2.0.0&q=maito"],["known-v21","?assortment=FI&locale=fi_FI&version=v2.1.0&q=maito"],["category-v2","?assortment=FI&locale=fi_FI&version=v2.0.0&q=*&category=10096095"],["category-v21","?assortment=FI&locale=fi_FI&version=v2.1.0&q=*&category=10096095"],["page-v2","?assortment=FI&locale=fi_FI&version=v2.0.0&pageId=10068374%2F10096095"]];
const results=await Promise.all(tests.map(async ([name,q])=>{try{const response=await fetch("https://www.lidl.fi/q/api/search"+q,{headers:{accept:"*/*","accept-language":"fi-FI,fi;q=0.9"},cache:"no-store",signal:AbortSignal.timeout(10000)});const t=await response.text();let o:unknown;try{o=JSON.parse(t)}catch{o=null}return{name,status:response.status,length:t.length,keys:o&&typeof o==="object"&&!Array.isArray(o)?Object.keys(o):[],sample:t.slice(0,650)}}catch(e){return{name,error:String(e)}}}));
return NextResponse.json({debugVersion:VERSION,readOnly:true,store,results});
}
