"use client";
import React from "react";
type Item={title?:string;name?:string;quantity?:number;[key:string]:any};
export type DesktopSavedList={id:string;name:string;createdAt:string;items:Item[]};
type Props={open:boolean;lists:DesktopSavedList[];currentCartCount:number;openedListId:string|null;onToggleList:(id:string)=>void;onSaveCurrentCart:()=>void;onRestoreList:(list:DesktopSavedList)=>void;onDeleteList:(id:string)=>void;onClose:()=>void};
export default function ZiiplyDesktopNotebookCard({open,lists,currentCartCount,openedListId,onToggleList,onSaveCurrentCart,onRestoreList,onDeleteList,onClose}:Props){
if(!open)return null;
return <div className="fixed inset-0 z-[95] grid place-items-center bg-[#17352a]/25 p-4">
<section role="dialog" aria-modal="true" aria-label="Ostelusvihko" className="relative flex h-[min(91vh,920px)] w-[min(89vw,1460px)] flex-col overflow-hidden rounded-[48px] border-[5px] border-[#76502e] bg-[#f7edcf] shadow-[0_30px_90px_rgba(20,40,31,.35)]">
<div className="pointer-events-none absolute inset-[5px] rounded-[39px] bg-center bg-no-repeat opacity-35" style={{backgroundImage:"url('/ui/cart/vihkonen.webp')",backgroundSize:"cover"}}/>
<div className="pointer-events-none absolute inset-[12px] rounded-[34px] border border-dashed border-[#bd9a61]/60"/>
<header className="relative z-10 shrink-0 border-b border-[#bba06d] px-8 pb-6 pt-9 text-center"><div className="text-[clamp(17px,1.55vw,24px)] font-black uppercase tracking-[.14em] text-[#7d6241]">TALLENNETUT OSTOSLISTAT</div><h2 className="mt-1 font-serif text-[clamp(48px,4.6vw,74px)] font-black italic leading-tight text-[#174c3a]">Ostelusvihko</h2></header>
{lists.length===0?<main className="relative z-10 flex min-h-0 flex-1 flex-col items-center justify-center px-6 text-center"><div className="text-[clamp(70px,7vw,108px)] leading-none">📒</div><h3 className="mt-7 font-serif text-[clamp(30px,3.2vw,49px)] font-black italic text-[#174c3a]">Ostelusvihko on vielä tyhjä</h3><p className="mt-4 text-[clamp(16px,1.5vw,23px)] font-bold text-[#76684f]">Tallenna nykyinen kori, niin löydät sen myöhemmin täältä.</p></main>:
<main className="relative z-10 min-h-0 flex-1 overflow-y-auto px-8 py-7"><div className="grid grid-cols-1 gap-4 xl:grid-cols-2">{lists.map(list=><article key={list.id} className="rounded-[22px] border-2 border-[#b89552] bg-[#fff6d9]/90 p-5"><div className="flex items-start justify-between gap-4"><div><div className="text-lg font-black text-[#26352b]">{list.name}</div><div className="mt-1 text-xs font-bold text-[#76684f]">{new Date(list.createdAt).toLocaleDateString("fi-FI")} · {list.items.reduce((sum,item)=>sum+Number(item.quantity||1),0)} tuotetta</div></div><button onClick={()=>onDeleteList(list.id)} className="rounded-full border border-[#9a4e3e] px-3 py-1 text-xs font-black text-[#8b3d31]">Poista</button></div><div className="mt-4 flex gap-2"><button onClick={()=>onToggleList(list.id)} className="rounded-full border border-[#315d45] bg-white px-4 py-2 text-xs font-black text-[#174c3a]">{openedListId===list.id?"Sulje tiedot":"Avaa vihko"}</button><button onClick={()=>onRestoreList(list)} className="rounded-full border border-[#315d45] bg-[#dfead4] px-4 py-2 text-xs font-black text-[#174c3a]">Palauta koriin</button></div><div className="mt-3 space-y-1">{(openedListId===list.id?list.items:list.items.slice(0,5)).map((item,index)=><div key={index} className="flex justify-between gap-4 text-xs font-bold"><span className="truncate">{item.title||item.name}</span><span>{Number(item.quantity||1)} kpl</span></div>)}{openedListId!==list.id&&list.items.length>5&&<div className="text-xs text-[#76684f]">+ {list.items.length-5} muuta tuotetta</div>}</div></article>)}</div></main>}
<footer className="relative z-10 flex shrink-0 items-center justify-center gap-5 px-5 pb-9 pt-5"><button onClick={onSaveCurrentCart} disabled={!currentCartCount} className="rounded-full border-[3px] border-[#91a17d] bg-[#fff3d4]/80 px-9 py-3 text-[clamp(16px,1.4vw,22px)] font-black text-[#537459] disabled:cursor-not-allowed disabled:opacity-50">Tallenna nykyinen kori</button><button aria-label="Sulje ostelusvihko" onClick={onClose} className="grid h-[72px] w-[72px] place-items-center rounded-full border-[4px] border-[#643a22] bg-[#a56c34] text-[32px] font-black text-white">×</button></footer>
</section></div>;
}
