"use client";
import React from "react";
type Item={title?:string;name?:string;quantity?:number;[key:string]:any};
export type DesktopSavedList={id:string;name:string;createdAt:string;items:Item[]};
type Props={open:boolean;lists:DesktopSavedList[];currentCartCount:number;openedListId:string|null;onToggleList:(id:string)=>void;onSaveCurrentCart:()=>void;onRestoreList:(list:DesktopSavedList)=>void;onDeleteList:(id:string)=>void;onClose:()=>void};
export default function ZiiplyDesktopNotebookCard({open,lists,currentCartCount,openedListId,onToggleList,onSaveCurrentCart,onRestoreList,onDeleteList,onClose}:Props){
if(!open)return null;
return <div className="fixed inset-0 z-[95] bg-[#17352a]/10">
<section role="dialog" aria-modal="true" aria-label="Ostelusvihko" className="fixed left-1/2 top-[calc(16vh+20px)] flex h-[min(76vh,760px)] w-[min(91vh,910px)] max-h-[calc(100dvh-48px)] max-w-[calc(100vw-32px)] -translate-x-1/2 flex-col overflow-hidden rounded-[32px] border-[4px] border-[#76502e] bg-[#f8edd7] shadow-[0_30px_90px_rgba(20,40,31,.35)]">


<header className="relative z-10 shrink-0 mx-9 border-b border-[#cbb583] px-8 pb-[18px] pt-[24px] text-center"><div className="text-[clamp(13px,1.1vw,17px)] font-black uppercase tracking-[.14em] text-[#7d6241]">TALLENNETUT OSTOSLISTAT</div><h2 className="mt-1 font-serif text-[clamp(38px,3vw,48px)] font-black italic leading-tight text-[#174c3a]">Ostelusvihko</h2></header>
{lists.length===0?<main className="relative z-10 flex min-h-0 flex-1 flex-col items-center justify-center px-6 pb-4 text-center"><div aria-hidden="true" className="relative h-[92px] w-[82px] rotate-[-8deg] rounded-[5px] border-[3px] border-[#7b5637] bg-[#e8d4a6] shadow-[5px_6px_0_#bba077]"><div className="absolute -left-[9px] top-[8px] flex flex-col gap-[12px]">{Array.from({length:5},(_,i)=><span key={i} className="h-[7px] w-[16px] rounded-full border-[2px] border-[#735b45] bg-[#d6c7a6]"/>)}</div><div className="mx-4 mt-5 border-b-2 border-[#b9a17d]"/><div className="mx-4 mt-3 border-b-2 border-[#b9a17d]"/><div className="mx-4 mt-3 border-b-2 border-[#b9a17d]"/></div><h3 className="mt-[18px] font-serif text-[clamp(26px,2.5vw,36px)] font-black italic text-[#174c3a]">Ostelusvihko on vielä tyhjä</h3><p className="mt-[12px] text-[clamp(14px,1.2vw,18px)] font-bold text-[#76684f]">Tallenna nykyinen kori, niin löydät sen myöhemmin täältä.</p></main>:
<main className="relative z-10 min-h-0 flex-1 overflow-y-auto px-8 py-7"><div className="grid grid-cols-1 gap-4 xl:grid-cols-2">{lists.map(list=><article key={list.id} className="rounded-[22px] border-2 border-[#b89552] bg-[#fff6d9]/90 p-5"><div className="flex items-start justify-between gap-4"><div><div className="text-lg font-black text-[#26352b]">{list.name}</div><div className="mt-1 text-xs font-bold text-[#76684f]">{new Date(list.createdAt).toLocaleDateString("fi-FI")} · {list.items.reduce((sum,item)=>sum+Number(item.quantity||1),0)} tuotetta</div></div><button onClick={()=>onDeleteList(list.id)} className="rounded-full border border-[#9a4e3e] px-3 py-1 text-xs font-black text-[#8b3d31]">Poista</button></div><div className="mt-4 flex gap-2"><button onClick={()=>onToggleList(list.id)} className="rounded-full border border-[#315d45] bg-white px-4 py-2 text-xs font-black text-[#174c3a]">{openedListId===list.id?"Sulje tiedot":"Avaa vihko"}</button><button onClick={()=>onRestoreList(list)} className="rounded-full border border-[#315d45] bg-[#dfead4] px-4 py-2 text-xs font-black text-[#174c3a]">Palauta koriin</button></div><div className="mt-3 space-y-1">{(openedListId===list.id?list.items:list.items.slice(0,5)).map((item,index)=><div key={index} className="flex justify-between gap-4 text-xs font-bold"><span className="truncate">{item.title||item.name}</span><span>{Number(item.quantity||1)} kpl</span></div>)}{openedListId!==list.id&&list.items.length>5&&<div className="text-xs text-[#76684f]">+ {list.items.length-5} muuta tuotetta</div>}</div></article>)}</div></main>}
<footer className="relative z-10 flex shrink-0 items-center justify-center gap-5 px-5 pb-[26px] pt-[10px]"><button onClick={onSaveCurrentCart} disabled={!currentCartCount} aria-label="Tallenna nykyinen kori" title="Tallenna nykyinen kori" className="rounded-full border-[3px] border-[#91a17d] bg-[#fff3d4]/80 px-9 py-3 text-[clamp(14px,1.2vw,18px)] font-black text-[#537459] disabled:cursor-not-allowed disabled:opacity-50"><svg aria-hidden="true" viewBox="0 0 72 64" className="h-[54px] w-[62px]" fill="none" xmlns="http://www.w3.org/2000/svg"><ellipse cx="36" cy="56" rx="28" ry="5" fill="#a58b69" opacity=".35"/><path d="M34 7c-7 0-12 5-12 12 0 6 4 10 8 12v7h12v-7c4-2 8-6 8-12 0-7-5-12-12-12h-4Z" fill="#9A6338" stroke="#603D28" strokeWidth="3" strokeLinejoin="round"/><path d="M30 13c-2 2-3 5-3 8" stroke="#DAB486" strokeWidth="3" strokeLinecap="round"/><path d="M29 36h14l4 9H25l4-9Z" fill="#C18A50" stroke="#603D28" strokeWidth="3" strokeLinejoin="round"/><path d="M16 45h40c3 0 5 2 5 5v5H11v-5c0-3 2-5 5-5Z" fill="#B77B43" stroke="#603D28" strokeWidth="3" strokeLinejoin="round"/><path d="M17 50h38" stroke="#E3BA84" strokeWidth="2" strokeLinecap="round"/><path d="M14 55h44" stroke="#603D28" strokeWidth="3" strokeLinecap="round"/></svg></button><button aria-label="Sulje ostelusvihko" onClick={onClose} className="grid h-[58px] w-[58px] place-items-center rounded-full border-[4px] border-[#643a22] bg-[#a56c34] text-[32px] font-black text-white">×</button></footer>
</section></div>;
}
