"use client";
import type { FormEvent } from "react";

type Product = { id?:string|number;ean?:string|number;name?:string;title?:string;productName?:string;pictureUrl?:string;imageUrl?:string;image?:string;__store?:string;__price?:number };
export default function DesktopJustiinaSearchCard({onClose,onOpenCart,query,onQueryChange,loading,onSearch,message,results,delay,onDelayChange}:{onClose:()=>void;onOpenCart:()=>void;query:string;onQueryChange:(value:string)=>void;loading:boolean;onSearch:()=>void;message:string;results:Product[];delay:0|1|2;onDelayChange:()=>void}){
return <div className="fixed left-1/2 top-[152px] z-50 flex h-[min(680px,calc(100dvh-190px))] w-[min(1120px,92vw)] -translate-x-1/2 flex-col overflow-hidden rounded-[28px] border-[3px] border-[#174c3a] bg-[#fff3cf] p-6 shadow-[0_28px_80px_rgba(34,54,43,.28)]">
  <div className="relative flex items-center justify-between gap-4"><button type="button" onClick={onClose} aria-label="Sulje Justiinan haku" className="rounded-full border-2 border-[#5a321b] bg-[#9a612d] px-4 py-2 text-[17px] font-black text-[#fff0c8]">×</button><div className="text-center"><div className="text-[11px] font-black uppercase tracking-[.28em] text-[#7c745d]">JUSTIINA · TUOTEHAKU</div><h2 className="font-serif text-[35px] font-black italic leading-none text-[#174c3a]">Tuotteet ja vertailu</h2></div><button type="button" onClick={onOpenCart} className="rounded-full border-[3px] border-[#0d633a] bg-[#118545] px-6 py-3 font-serif text-[19px] font-black italic text-[#fff3d2]">Vihkonen</button></div>
  <div className="mx-auto mt-4 flex w-full max-w-[850px] min-h-0 flex-1 flex-col">
    <div className="grid grid-cols-[1fr_130px] items-center gap-4"><div className="flex items-center justify-center gap-5 rounded-[24px] border-2 border-[#d0aa58] bg-[#fff8dd] p-3"><img src="/assistants/justiina.png" alt="Justiina" className="h-[120px] w-[120px] object-contain"/><div><div className="font-serif text-[25px] font-black italic text-[#174c3a]">Justiina</div><div className="text-[13px] font-bold text-[#75664e]">Etsii tuotteet valituista kaupoista</div></div></div><button type="button" onClick={onDelayChange} className="rounded-[22px] border-2 border-[#d0aa58] bg-[#fff8dd] p-3 text-center"><div className="text-[32px]">⏱</div><div className="text-[11px] font-black uppercase text-[#174c3a]">Hakutahti</div><div className="text-[12px] font-black text-[#75664e]">{delay===2?"Normaali · 2 s":delay===1?"Nopea · 1 s":"Heti · 0 s"}</div></button></div>
    <form onSubmit={(e:FormEvent)=>{e.preventDefault();onSearch()}} className="mt-4 flex gap-3"><input autoFocus value={query} onChange={e=>onQueryChange(e.target.value)} placeholder="Kirjoita tuote tai ostoslista" aria-label="Hae tuotteita" className="min-w-0 flex-1 rounded-[24px] border-[3px] border-[#b89959] bg-[#fffdf5] px-5 py-3 text-center font-serif text-[23px] font-black text-[#6f6657] outline-none placeholder:text-[#8b806e]"/><button type="submit" disabled={loading||!query.trim()} className="rounded-[22px] border-[3px] border-[#0d633a] bg-[#118545] px-7 text-[17px] font-black text-white disabled:opacity-40">{loading?"Haetaan…":"Hae"}</button></form>
    <div role="status" aria-live="polite" className="mt-3 min-h-[24px] text-center text-[13px] font-black text-[#765f3f]">{message||(!results.length?"Kirjoita tuote, tuoteryhmä tai ostoslista.":"")}</div>
    <div className="mt-2 min-h-0 flex-1 overflow-y-auto">{results.length>0&&<div className="grid grid-cols-2 gap-2 pr-1">{results.map((p,i)=><div key={String(p.id||p.ean||i)} className="flex min-h-[82px] items-center gap-3 rounded-[18px] border-2 border-[#d0aa58] bg-[#fffaf0] p-2 text-left">{(p.pictureUrl||p.imageUrl||p.image)&&<img src={p.pictureUrl||p.imageUrl||p.image} alt="" className="h-14 w-14 rounded-xl bg-white object-contain"/>}<div className="min-w-0 flex-1"><div className="line-clamp-2 text-[12px] font-black text-[#26352b]">{p.name||p.title||p.productName}</div><div className="mt-1 text-[10px] font-bold text-[#76684f]">{p.__store}</div></div>{Number(p.__price)>0&&<div className="text-[15px] font-black text-[#174c3a]">{Number(p.__price).toFixed(2).replace(".",",")} €</div>}</div>)}</div>}</div>
    <div className="mt-3 grid grid-cols-2 gap-4"><button type="button" disabled title="Äänihaku ei ole vielä käytössä desktopissa" className="rounded-[20px] border-[3px] border-[#6e5b32] bg-[#2c3429] px-5 py-3 text-[16px] font-black text-[#ffe0a0] opacity-55">🎙️ Äänitä · tulossa</button><button type="button" disabled title="Kamerahaku ei ole vielä käytössä desktopissa" className="rounded-[20px] border-[3px] border-[#6e5b32] bg-[#2c3429] px-5 py-3 text-[16px] font-black text-[#ffe0a0] opacity-55">📷 Filmaa · tulossa</button></div>
  </div>
</div>
}
