"use client";
import type { FormEvent } from "react";

type Product = { id?:string|number;ean?:string|number;name?:string;title?:string;productName?:string;pictureUrl?:string;imageUrl?:string;image?:string;__store?:string;__price?:number };
export default function DesktopJustiinaSearchCard({onClose,onOpenCart,query,onQueryChange,loading,onSearch,message,results,delay,onDelayChange,onAddToCart}:{onClose:()=>void;onOpenCart:()=>void;query:string;onQueryChange:(value:string)=>void;loading:boolean;onSearch:()=>void;message:string;results:Product[];delay:0|1|2;onDelayChange:()=>void;onAddToCart:(product:Product)=>void}){
return <div className="fixed left-1/2 top-[150px] z-50 flex max-h-[calc(100dvh-170px)] w-[min(570px,94vw)] -translate-x-1/2 flex-col overflow-hidden rounded-[28px] border-[3px] border-[#174c3a] bg-[#fff3cf] p-4 shadow-[0_28px_80px_rgba(34,54,43,.28)]">
  <div className="relative flex items-center justify-center px-10 text-center"><button type="button" onClick={onClose} aria-label="Sulje Justiinan haku" className="absolute left-0 top-0 rounded-full border-2 border-[#5a321b] bg-[#9a612d] px-3 py-1.5 text-[17px] font-black text-[#fff0c8]">×</button><div><div className="text-[10px] font-black uppercase tracking-[.22em] text-[#7c745d]">JUSTIINA · TUOTEHAKU</div><h2 className="font-serif text-[25px] font-black italic leading-tight text-[#174c3a]">Tuotteet ja vertailu</h2></div></div>
  <div className="mt-4 flex min-h-0 flex-col">
    <button type="button" onClick={onDelayChange} className="self-end rounded-xl border border-[#d0aa58] bg-[#fff8dd] px-3 py-2 text-[12px] font-black text-[#174c3a]">⏱ Hakutahti: {delay===2?"Normaali · 2 s":delay===1?"Nopea · 1 s":"Heti · 0 s"}</button>
    <form onSubmit={(e:FormEvent)=>{e.preventDefault();onSearch()}} className="mt-3 flex gap-2"><input autoFocus value={query} onChange={e=>onQueryChange(e.target.value)} placeholder="Kirjoita tuote tai ostoslista" aria-label="Hae tuotteita" className="min-w-0 flex-1 rounded-[24px] border-[3px] border-[#b89959] bg-[#fffdf5] px-4 py-3 text-center font-serif text-[17px] font-black text-[#6f6657] outline-none placeholder:text-[#8b806e]"/>{query && <button type="button" onClick={()=>onQueryChange("")} aria-label="Tyhjennä haku" className="rounded-xl border border-[#b89959] bg-[#fff8dd] px-3 font-black text-[#674c2e]">✕</button>}</form>
    <div role="status" aria-live="polite" className="mt-3 min-h-[24px] text-center text-[13px] font-black text-[#765f3f]">{message||(!results.length?"Kirjoita tuote, tuoteryhmä tai ostoslista.":"")}</div>
    <div className="mt-2 max-h-[230px] min-h-0 overflow-y-auto">{results.length>0&&<div className="grid grid-cols-1 gap-2 pr-1">{results.map((p,i)=><div key={String(p.id||p.ean||i)} className="flex min-h-[82px] items-center gap-3 rounded-[18px] border-2 border-[#d0aa58] bg-[#fffaf0] p-2 text-left">{(p.pictureUrl||p.imageUrl||p.image)&&<img src={p.pictureUrl||p.imageUrl||p.image} alt="" className="h-14 w-14 rounded-xl bg-white object-contain"/>}<div className="min-w-0 flex-1"><div className="line-clamp-2 text-[12px] font-black text-[#26352b]">{p.name||p.title||p.productName}</div><div className="mt-1 text-[10px] font-bold text-[#76684f]">{p.__store}</div></div><button type="button" onClick={()=>onAddToCart(p)} aria-label="Lisää ostoskoriin" title="Lisää ostoskoriin" className="rounded-lg border border-[#0d633a] bg-[#118545] px-2 py-2 text-white">🛒</button>{Number(p.__price)>0&&<div className="text-[15px] font-black text-[#174c3a]">{Number(p.__price).toFixed(2).replace(".",",")} €</div>}</div>)}</div>}</div>
    <div className="mt-4 grid grid-cols-2 gap-2"><button type="button" disabled title="Äänihaku ei ole vielä käytössä desktopissa" className="rounded-[20px] border-[3px] border-[#6e5b32] bg-[#2c3429] px-2 py-2 text-[12px] font-black text-[#ffe0a0] opacity-55">🎙️ Äänitä · tulossa</button><button type="button" disabled title="Kamerahaku ei ole vielä käytössä desktopissa" className="rounded-[20px] border-[3px] border-[#6e5b32] bg-[#2c3429] px-5 py-3 text-[16px] font-black text-[#ffe0a0] opacity-55">📷 Filmaa · tulossa</button></div>
  </div>
</div>
}
