"use client";
import type { FormEvent } from "react";

type Product = { id?:string|number;ean?:string|number;name?:string;title?:string;productName?:string;pictureUrl?:string;imageUrl?:string;image?:string;__store?:string;__price?:number };
export default function DesktopJustiinaSearchCard({onClose,onOpenCart,query,onQueryChange,loading,onSearch,message,results,delay,onDelayChange,onAddToCart,onAddInputToCart,onReopenResults,onOpenScanner}:{onClose:()=>void;onOpenCart:()=>void;query:string;onQueryChange:(value:string)=>void;loading:boolean;onSearch:()=>void;message:string;results:Product[];delay:0|1|2;onDelayChange:()=>void;onAddToCart:(product:Product)=>void;onAddInputToCart:(text:string)=>void;onReopenResults:()=>void;onOpenScanner:()=>void}){
return <div className="fixed left-1/2 top-[127px] z-50 flex max-h-[calc(100dvh-170px)] w-[min(522px,94vw)] -translate-x-1/2 flex-col overflow-hidden rounded-[28px] border-[3px] border-[#174c3a] bg-[#fff3cf] p-4 shadow-[0_28px_80px_rgba(34,54,43,.28)]">
  <div className="relative flex items-center justify-center px-10 text-center"><button type="button" onClick={onClose} aria-label="Sulje Justiinan haku" className="absolute left-0 top-0 rounded-full border-2 border-[#5a321b] bg-[#9a612d] px-3 py-1.5 text-[17px] font-black text-[#fff0c8]">×</button><div><div className="text-[10px] font-black uppercase tracking-[.22em] text-[#7c745d]">JUSTIINA · TUOTEHAKU</div><h2 className="font-serif text-[25px] font-black italic leading-tight text-[#174c3a]">Tuotteet ja vertailu</h2></div></div>
  <div className="mt-4 flex min-h-0 flex-col">
    <button type="button" onClick={onDelayChange} className="self-end rounded-xl border border-[#d0aa58] bg-[#fff8dd] px-3 py-2 text-[12px] font-black text-[#174c3a]">⏱ Hakutahti: {delay===2?"Normaali · 2 s":delay===1?"Nopea · 1 s":"Heti · 0 s"}</button>
    <form onSubmit={(e:FormEvent)=>{e.preventDefault();if(query.trim())onAddInputToCart(query)}} className="mt-3"><div className="relative"><input autoFocus value={query} onChange={e=>onQueryChange(e.target.value)} placeholder="Kirjoita tuote tai ostoslista" aria-label="Hae tuotteita" className="w-full min-w-0 rounded-[24px] border-[3px] border-[#b89959] bg-[#fffdf5] px-4 py-3 pr-[108px] text-center font-serif text-[17px] font-black text-[#6f6657] outline-none placeholder:text-[#8b806e]"/>{query.trim() && <><button type="button" onClick={()=>onQueryChange("")} aria-label="Tyhjennä hakukenttä" title="Tyhjennä hakukenttä" className="absolute right-[58px] top-1/2 grid h-10 w-10 -translate-y-1/2 place-items-center rounded-full border-2 border-[#d0aa4f] bg-[#fff1c9] text-[19px]">🧽</button><button type="button" onClick={()=>onAddInputToCart(query)} aria-label="Lisää kirjoitettu ostoslistaan" title="Lisää kirjoitettu ostoslistaan" className="absolute right-[9px] top-1/2 grid h-10 w-10 -translate-y-1/2 place-items-center rounded-full border-2 border-[#477350] bg-[#e2edcf] text-[20px]">🧺</button></>}</div></form>
    {results.length>0 ? <button type="button" onClick={onReopenResults} aria-label="Avaa tehdyn haun tuotevalinta" className="mt-2 rounded-xl border border-[#d0aa58] bg-[#fff8dd] px-3 py-2 text-center text-[12px] font-bold text-[#174c3a] hover:bg-[#f7e8b9]">Tehty haku: <span className="font-black">{query.trim()}</span> · {results.length} tuotetta löytyi <span aria-hidden="true">→</span></button> : <div role="status" aria-live="polite" className="mt-2 min-h-[24px] text-center text-[13px] font-black text-[#765f3f]">{message||"Kirjoita tuote, tuoteryhmä tai ostoslista."}</div>}
    <div className="mt-4 flex items-center gap-2"><button type="button" disabled title="Äänihaku ei ole vielä käytössä desktopissa" className="flex min-h-[54px] min-w-0 flex-1 items-center justify-center rounded-[18px] border-[3px] border-[#6e5b32] bg-[#2c3429] px-2 py-2 text-center text-[12px] font-black text-[#ffe0a0] opacity-55">🎙️ Äänitä · tulossa</button><button type="button" onClick={onOpenCart} aria-label="Avaa ostoskori" title="Avaa ostoskori" className="flex h-[62px] w-[62px] shrink-0 items-center justify-center rounded-full border-[4px] border-[#7b6034] bg-[#d8c08c] shadow-[0_5px_12px_rgba(0,0,0,0.18),inset_0_2px_0_rgba(255,255,255,0.55)]"><span className="flex h-[46px] w-[46px] items-center justify-center rounded-full border-[2px] border-[#efe2b8] bg-[#16472c] text-[26px] leading-none">🧺</span></button><button type="button" onClick={onOpenScanner} title="Avaa EAN-skanneri" className="flex min-h-[54px] min-w-0 flex-1 items-center justify-center rounded-[18px] border-[3px] border-[#6e5b32] bg-[#2c3429] px-2 py-2 text-center text-[13px] font-black text-[#ffe0a0]">▥ EAN / Skannaa</button></div>
  </div>
</div>
}
